name: Update gist
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: woochanleee/daily_school_meals@main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BREAKFAST_GIST_ID: ${{ secrets.BREAKFAST_GIST_ID }}
          LAUNCH_GIST_ID: ${{ secrets.LAUNCH_GIST_ID }}
          DINNER_GIST_ID: ${{ secrets.DINNER_GIST_ID }}  
